name: score_norm_fairness
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - scikit-learn
  - scikit-image
  - pandas
  - matplotlib
  - h5py
  - tqdm
  - dask
  - setuptools
  - pip
  # - scipy
  # - numpy
  - pip:
    - dask
    - dask[dataframe]
    - opencv-python
    - -e . # Install this package as well
